Controllers/GenderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HolidayTracker.Areas.Identity.Extensions;
using HolidayTracker.Models.Gender;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

// Gender Controller

namespace HolidayTracker.Controllers
{
    // Access control using Role-based Authorisation
    [Authorize(Roles = "Admin, Manager, SystemAdmin")]
    public class GenderController : Controller
    {
        
        private readonly HolidayTracker.Data.ApplicationDbContext _context;
        public GenderController(HolidayTracker.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        // Action method to display Gender view
        public async Task<IActionResult> Index(string sortOrder,
            string currentFilter, string searchString, int? pageIndex)
        {
            HolidayTracker.Views.Genders.IndexModel pageData = new Views.Genders.IndexModel(_context);
            
            int currentUsersCompanyId = User.Identity.GetCompanyId();
            pageData.CurrentSort = sortOrder;
            pageData.NameSort = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            pageData.CodeSort = sortOrder == "Code" ? "code_desc" : "Code";
            if (searchString != null)
            {
                pageIndex = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            pageData.CurrentFilter = searchString;

            IQueryable<Gender> dbdata = _context.Genders.Where(x => x.CompanyId == currentUsersCompanyId);
            if (!String.IsNullOrEmpty(searchString))
            {
                dbdata = dbdata.Where(s => s.Name.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    dbdata = dbdata.OrderByDescending(s => s.Name);
                    break;
                case "Code":
                    dbdata = dbdata.OrderBy(s => s.Id);
                    break;
                case "code_desc":
                    dbdata = dbdata.OrderByDescending(s => s.Id);
                    break;
                default:
                    dbdata = dbdata.OrderBy(s => s.Name);
                    break;
            }

            int pageSize = 10;
            pageData.Gender = await PaginatedList<Gender>.CreateAsync(
                dbdata.AsNoTracking(), pageIndex ?? 1, pageSize);

            return View(pageData);
        }

        // HttpGet method to display Gender Edit view
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            int currentUsersCompanyId = User.Identity.GetCompanyId();

            Gender gender = await _context.Genders.FirstOrDefaultAsync(x => x.Id == id && x.CompanyId == currentUsersCompanyId);

            if (gender == null)
            {
                return NotFound();
            }
            return View(gender);
        }

        // HttpPost method to edit genders
        [HttpPost]
        public async Task<IActionResult> Edit(Gender gen)
        {
            if (!ModelState.IsValid)
            {
                return View(gen);
            }

            _context.Attach(gen).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!GenderExists(gen.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction("Index");
        }

        // A boolean method to check if any genders exist
        private bool GenderExists(int id)
        {
            return _context.Genders.Any(g => g.Id == id);
        }

        // HttpGet method to display create Genders view
        [HttpGet]
        public IActionResult Create()
        {
            return View(new Gender());
        }

        // HttpPost method to create genders
        [HttpPost]
        public async Task<IActionResult> Create(Gender gen)
        {
            if (!ModelState.IsValid)
            {
                return View(gen);
            }

            int currentUsersCompanyId = User.Identity.GetCompanyId();

            gen.CompanyId = currentUsersCompanyId;

            _context.Genders.Add(gen);

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!GenderExists(gen.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction("Index");
        }

        // Action method to return genders created for the company of the currently logged in user
        // It is displayed in the Details view
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            int currentUsersCompanyId = User.Identity.GetCompanyId();

            Gender gender = await _context.Genders.FirstOrDefaultAsync(x => x.Id == id && x.CompanyId == currentUsersCompanyId && x.IsDeleted == false);

            if (gender == null)
            {
                return NotFound();
            }
            return View(gender);
        }

        // HttpGet method to display Delete Gender view
        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            int currentUsersCompanyId = User.Identity.GetCompanyId();

            Gender gender = await _context.Genders.FirstOrDefaultAsync(x => x.Id == id && x.CompanyId == currentUsersCompanyId);

            if (gender == null)
            {
                return NotFound();
            }
            return View(gender);
        }

        // HttpPost method to delete genders
        [HttpPost]
        public async Task<IActionResult> Delete(Gender gen)
        {
            if (!ModelState.IsValid)
            {
                return View(gen);
            }

            gen.IsDeleted = true;

            _context.Attach(gen).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!GenderExists(gen.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction("Index");
        }
    }
}

Controllers/LocationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HolidayTracker.Areas.Identity.Extensions;
using HolidayTracker.Models.Location;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

// Location Controller

namespace HolidayTracker.Controllers
{
    // Access control using Role-based Authorisation
    [Authorize(Roles = "Admin, Manager, SystemAdmin")]
    public class LocationController : Controller
    {

        private readonly HolidayTracker.Data.ApplicationDbContext _context;
        public LocationController(HolidayTracker.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        // Action method to display Locations view
        public async Task<IActionResult> Index(string sortOrder,
            string currentFilter, string searchString, int? pageIndex)
        {
            HolidayTracker.Views.Locations.IndexModel pageData = new Views.Locations.IndexModel(_context);
            
            int currentUsersCompanyId = User.Identity.GetCompanyId();
            pageData.CurrentSort = sortOrder;
            pageData.NameSort = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            pageData.CodeSort = sortOrder == "Code" ? "code_desc" : "Code";
            if (searchString != null)
            {
                pageIndex = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            pageData.CurrentFilter = searchString;

            IQueryable<Location> dbdata = _context.Locations.Where(x => x.CompanyId == currentUsersCompanyId);
            if (!String.IsNullOrEmpty(searchString))
            {
                dbdata = dbdata.Where(s => s.LocationName.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    dbdata = dbdata.OrderByDescending(s => s.LocationName);
                    break;
                case "Code":
                    dbdata = dbdata.OrderBy(s => s.LocationCode);
                    break;
                case "code_desc":
                    dbdata = dbdata.OrderByDescending(s => s.LocationCode);
                    break;
                default:
                    dbdata = dbdata.OrderBy(s => s.LocationName);
                    break;
            }

            int pageSize = 10;
            pageData.Location = await PaginatedList<Location>.CreateAsync(
                dbdata.AsNoTracking(), pageIndex ?? 1, pageSize);

            return View(pageData);
        }

        // HttpGet method to display Locations Edit view
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            int currentUsersCompanyId = User.Identity.GetCompanyId();

            Location location = await _context.Locations.FirstOrDefaultAsync(x => x.Id == id && x.CompanyId == currentUsersCompanyId);

            if (location == null)
            {
                return NotFound();
            }
            return View(location);
        }

        // HttpPost method to edit locations
        [HttpPost]
        public async Task<IActionResult> Edit(Location loc)
        {
            if (!ModelState.IsValid)
            {
                return View(loc);
            }

            _context.Attach(loc).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!LocationExists(loc.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }                                
            }
            return RedirectToAction("Index");
        }

        // A boolean method to check if any locations exist
        private bool LocationExists(int id)
        {
            return _context.Locations.Any(l => l.Id == id);
        }

        // HttpGet method to display Delete Locations view
        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            int currentUsersCompanyId = User.Identity.GetCompanyId();

            Location location = await _context.Locations.FirstOrDefaultAsync(x => x.Id == id && x.CompanyId == currentUsersCompanyId);

            if (location == null)
            {
                return NotFound();
            }
            return View(location);
        }

        // HttpPost method to delete locations
        [HttpPost]
        public async Task<IActionResult> Delete(Location loc)
        {
            if (!ModelState.IsValid)
            {
                return View(loc);
            }

            loc.IsDeleted = true;

            _context.Attach(loc).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!LocationExists(loc.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }                                
            }
            return RedirectToAction("Index");
        }

        // HttpGet method to display create Locations view
        [HttpGet]
        public IActionResult Create()
        {
            return View(new Location());
        }

        // HttpPost method to create locations
        [HttpPost]
        public async Task<IActionResult> Create(Location loc)
        {
            if (!ModelState.IsValid)
            {
                return View(loc);
            }

            int currentUsersCompanyId = User.Identity.GetCompanyId();

            loc.CompanyId = currentUsersCompanyId;

            _context.Locations.Add(loc);

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!LocationExists(loc.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }                                
            }
            return RedirectToAction("Index");
        }

        // Method to return locations created for the company of the currently logged in user
        // It is displayed in the Details view
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            int currentUsersCompanyId = User.Identity.GetCompanyId();

            Location location = await _context.Locations.FirstOrDefaultAsync(x => x.Id == id && x.CompanyId == currentUsersCompanyId && x.IsDeleted == false);

            if (location == null)
            {
                return NotFound();
            }
            return View(location);
        }
    }
}

Views/Shared/_Footer.cshtml
<div class="footer">
    <div class="float-right">
        TECHNOLOGICAL UNIVERSITY DUBLIN
    </div>
    <div>
        &copy; <span id="year"></span> - HolidayTracker - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</div>

<script>
    document.getElementById("year").innerHTML = new Date().getFullYear();
</script>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>HT - @ViewData["Title"]</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Add local styles, mostly for plugins css file -->
    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.css" />
        <link rel="stylesheet" href="~/css/animate.css" />
        <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css" />
        <link rel="stylesheet" href="~/css/animate.css" />
        <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    </environment>


</head>
<body>
    <!-- Skin configuration box -->
    <!-- <partial name="_SkinConfig" /> -->
    <!-- Wrapper-->
    <div id="wrapper" class="@*@Html.PageClass()*@">

        <!-- Navigation -->
        <partial name="_Navigation" />

        <!-- Page wraper -->
        <div id="page-wrapper" class="gray-bg @ViewBag.SpecialClass">

            <!-- Top Navbar -->
            <partial name="_LoginPartial" />

            <!-- Main view  -->
            @RenderBody()

            <!-- Footer -->
            <partial name="_Footer" />

        </div>
        <!-- End page wrapper-->

    </div>
    <!-- End wrapper-->

    @RenderSection("toast", required: false)

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/Popper/popper.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/metisMenu/dist/jquery.metisMenu.js"></script>
        <script src="~/lib/slimScroll/jquery.slimscroll.js"></script>
        <script src="~/lib/pace/pace.js"></script>
        <script src="~/js/script.js" asp-append-version="true"></script>

        <!-- Only for demo purpose -->
        <script src="~/js/skin.config.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/Popper/popper.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
        <script src="~/lib/metisMenu/dist/jquery.metisMenu.js"></script>
        <script src="~/lib/pace/pace.min.js"></script>
        <script src="~/lib/slimScroll/jquery.slimscroll.min.js"></script>
        <script src="~/js/script.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_Navigation.cshtml
@*
    **********************************************
    Navigation Bar used as side bar
    Nav Items Secured by ASP.NET Core Identity
    Access blocked to unathorised logged in users
    using Role-based Authentication
    **********************************************
*@
@using Microsoft.AspNetCore.Identity
@using HolidayTracker.Areas.Identity.Data;
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <img class="rounded-circle" src="~/Images/ht_logo_2.png" alt="HT logo" />
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="block m-t-xs font-bold">Holiday Tracker</span>
                            <span class="text-muted text-xs block">Hello @UserManager.GetUserName(User) <b class="caret"></b></span>
                        </a>
                        <ul class="dropdown-menu animated fadeInRight m-t-xs" style="position: absolute; top: 91px; left: 0px; will-change: top, left;">
                            <li><a class="dropdown-item" asp-area="Identity" asp-page="/Account/Manage/Index">Profile</a></li>
                            <li class="dropdown-divider"></li>
                            <li><a class="dropdown-item" asp-area="Identity" asp-page="/Account/Logout">Logout</a></li>
                        </ul>
                    }
                </div>
                <div class="logo-element">
                    HT
                </div>
            </li>
            <li class="nav-item">
                <a asp-area="" asp-controller="Home" asp-action="Index"><i class="fa fa-globe"></i> <span class="nav-label" data-i18n="nav.miscellaneous">Home</span></a>
            </li>
            <li class="nav-item dropdown">
                @if (User.Identity.IsAuthenticated)
                {
                    if (User.IsInRole("Manager"))
                    {
                        <a href="#"><i class="fa fa-flask"></i> <span class="nav-label" data-i18n="nav.uielements">Company Settings</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level collapse">

                            <li class="nav-link"><a asp-area="" asp-controller="Location" asp-action="Index">Location</a></li>

                            <li class="nav-link"><a asp-area="" asp-controller="Department" asp-action="Index">Departments</a></li>

                            <li class="nav-link"><a asp-area="" asp-controller="Gender" asp-action="Index">Genders</a></li>

                            <li class="nav-link"><a asp-area="" asp-controller="RequestType" asp-action="Index">Request Type</a></li>

                            <li class="nav-link"><a asp-area="" asp-controller="Employee" asp-action="Index">Employees</a></li>

                            <li class="nav-link"><a asp-area="" asp-controller="Allowance" asp-action="Index">Allowance</a></li>
                        </ul>
                    }
                }
            </li>
            <li class="nav-item">
                @if (User.Identity.IsAuthenticated)
                {
                    if (User.IsInRole("Employee"))
                    {
                        <a asp-area="" asp-controller="Home" asp-action="Dashboard"><i class="fa fa-th-large"></i> <span class="nav-label" data-i18n="nav.dashboard">Dashboard</span></a>
                    }

                }
            </li>
            <li class="nav-item">
                @if (User.Identity.IsAuthenticated)
                {
                    if (User.IsInRole("Approver"))
                    {
                        <a asp-area="" asp-controller="Approver" asp-action="Index"><i class="fa fa-edit"></i> <span class="nav-label" data-i18n="nav.forms">Requests</span></a>
                    }

                }
            </li>
            <li class="nav-item">
                @if (User.Identity.IsAuthenticated)
                {
                    if (User.IsInRole("Admin"))
                    {
                        <a asp-area="" asp-controller="Admin" asp-action="Index"><i class="fa fa-bar-chart-o"></i> <span class="nav-label" data-i18n="nav.graphs">Billing</span></a>
                    }

                }
            </li>
            <li class="nav-item">
                <a asp-area="" asp-controller="Home" asp-action="Privacy"><i class="fa fa-laptop"></i> <span class="nav-label" data-i18n="nav.gridoptions">Privacy</span></a>
            </li>
            <li class="nav-item">
                <a asp-area="" asp-controller="Home" asp-action="Contact"><i class="fa fa-envelope"></i> <span class="nav-label" data-i18n="nav.mailbox">Contact Us</span></a>
            </li>
            <li class="nav-item">
                <a asp-area="" asp-controller="Home" asp-action="About"><i class="fa fa-star"></i> <span class="nav-label" data-i18n="nav.mailbox">About</span></a>
            </li>
        </ul>
    </div>
</nav>

Views/Shared/_TopNavbar.cshtml
<div class="row border-bottom">
    <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
            
        </div>
        <ul class="nav navbar-top-links navbar-right">            
            <li>
                <a href="@Url.Action("Login", "Pages")">
                    <i class="fa fa-sign-out"></i> Log out
                </a>
            </li>
        </ul>
    </nav>
</div>