Controllers/ApproverController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using HolidayTracker.Areas.Identity.Extensions;
using HolidayTracker.Models.Employee;
using HolidayTracker.Models.Request;
using HolidayTracker.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

// Approver Controller

namespace HolidayTracker.Controllers
{
    // Access control using Role-based Authorisation
    [Authorize(Roles = "Approver, Manager, SystemAdmin")]
    public class ApproverController : Controller
    {

        
        private readonly HolidayTracker.Data.ApplicationDbContext _context;

        public ApproverController( HolidayTracker.Data.ApplicationDbContext context)
        {
            
            _context = context;
        }

        // Method to display all pending request of Employees that the logged in user is an Approver for
        [HttpGet]
        public IActionResult Index()
        {

            int currentUsersCompanyId = User.Identity.GetCompanyId();

            int currentUserId = _context.Employees.Where(x => x.Email.ToLower() == HttpContext.User.Identity.Name.ToLower()).Select(x => x.Id).FirstOrDefault();


            ApprovalsViewModel viewModel = new ApprovalsViewModel();
            
            List<int> myEmployeesId = _context.Employees.Where(x => x.ApproverId == currentUserId).Select(x => x.Id).ToList();

            viewModel.Requests = _context.Requests.Include(r => r.RequestType).Include(e => e.Employee).Where(x => myEmployeesId.Contains(x.EmployeeId) && x.Status == 0).ToList();

            return View(viewModel);
        }

        // A HttpGet method display the request history for the logged in user
        [HttpGet]
        public IActionResult DisplayAllRequests()
        {

            int currentUsersCompanyId = User.Identity.GetCompanyId();

            int currentUserId = _context.Employees.Where(x => x.Email.ToLower() == HttpContext.User.Identity.Name.ToLower()).Select(x => x.Id).FirstOrDefault();


            ApprovalsViewModel viewModel = new ApprovalsViewModel();

            List<int> myEmployeesId = _context.Employees.Where(x => x.ApproverId == currentUserId).Select(x => x.Id).ToList();

            viewModel.Requests = _context.Requests.Include(r => r.RequestType).Include(e => e.Employee).Where(x => myEmployeesId.Contains(x.EmployeeId) && x.Status > 0).ToList();

            return View(viewModel);
        }

        // HttpPost method to approve a request
        [HttpPost]
        public async Task<IActionResult> ApproveRequest(int Id)
        {

            int currentUsersCompanyId = User.Identity.GetCompanyId();

            int currentUserId = _context.Employees.Where(x => x.Email.ToLower() == HttpContext.User.Identity.Name.ToLower()).Select(x => x.Id).FirstOrDefault();


            List<int> myEmployeesId = _context.Employees.Where(x => x.ApproverId == currentUserId).Select(x => x.Id).ToList();

            Request requestPending = _context.Requests.Where(r => r.Id == Id && myEmployeesId.Contains(r.EmployeeId)).FirstOrDefault();

            if (requestPending != null)
            {
                requestPending.Status = 1;

                _context.Attach(requestPending).State = EntityState.Modified;

                try
                {
                    await _context.SaveChangesAsync();

                    //  When I want to return success:
                    Response.StatusCode = (int)HttpStatusCode.OK;
                    return Json("Saved!");
                }
                catch (DbUpdateConcurrencyException)
                {
                    Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    return Json("Failed"); ;
                }
            }
            else
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json("Failed");
            }
        }

        //HttpPOst method to reject a request
        [HttpPost]
        public async Task<IActionResult> RejectRequest(int Id)
        {

            int currentUsersCompanyId = User.Identity.GetCompanyId();

            int currentUserId = _context.Employees.Where(x => x.Email.ToLower() == HttpContext.User.Identity.Name.ToLower()).Select(x => x.Id).FirstOrDefault();

            
            List<int> myEmployeesId = _context.Employees.Where(x => x.ApproverId == currentUserId).Select(x => x.Id).ToList();

            Request requestPending = _context.Requests.Where(r => r.Id == Id && myEmployeesId.Contains(r.EmployeeId)).FirstOrDefault();

            if (requestPending != null)
            {
                requestPending.Status = 4;

                _context.Attach(requestPending).State = EntityState.Modified;

                try
                {
                    await _context.SaveChangesAsync();

                    //  When I want to return success:
                    Response.StatusCode = (int)HttpStatusCode.OK;
                    return Json("Saved!");
                }
                catch (DbUpdateConcurrencyException)
                {
                    Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    return Json("Failed"); ;
                }
            }
            else
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json("Failed");
            }
        }

        // HttpPost method to cancel a request
        [HttpPost]
        public async Task<IActionResult> CancelRequest(int Id)
        {
            
            int currentUsersCompanyId = User.Identity.GetCompanyId();

            int currentUserId = _context.Employees.Where(x => x.Email.ToLower() == HttpContext.User.Identity.Name.ToLower()).Select(x => x.Id).FirstOrDefault();

            
            List<int> myEmployeesId = _context.Employees.Where(x => x.ApproverId == currentUserId).Select(x => x.Id).ToList();

            Request requestPending = _context.Requests.Where(r => r.Id == Id && myEmployeesId.Contains(r.EmployeeId)).FirstOrDefault();

            if (requestPending != null)
            {
                requestPending.Status = 3;

                _context.Attach(requestPending).State = EntityState.Modified;

                try
                {
                    await _context.SaveChangesAsync();

                    //  When I want to return success:
                    Response.StatusCode = (int)HttpStatusCode.OK;
                    return Json("Saved!");
                }
                catch (DbUpdateConcurrencyException)
                {
                    Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    return Json("Failed"); ;
                }
            }
            else
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json("Failed");
            }
        }
    }
}

Views/Approver/DisplayAllRequests.cshtml
@*
    *******************************************
    A view displaying a the history of requests
    for an approver user's assigned employees
    *******************************************
*@
@model HolidayTracker.ViewModels.ApprovalsViewModel;
@{
    ViewData["Title"] = "Request History";
}

<div class="text-center">
    <h4 class="display-4">Request History</h4>
    <p>This is the history of employee requests assigned to you</p>
</div>

<h2>Request History</h2>
<p>
    <a asp-action="Index">Back to Pending</a>
</p>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox ">
                <div class="ibox-title">
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">

                    <table class="table table-striped table-bordered table-hover dataTables-example">
                        <thead>
                            <tr>
                                <th>Requested By</th>
                                <th>Request Type</th>
                                <th>From</th>
                                <th>To</th>
                                <th>Requested Amount</th>
                                <th>Status</th>
                                <th>Comments</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Requests)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Employee.DisplayName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.RequestType.RequestTypeName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.From)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.To)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.RequestAmount)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.DisplayStatus)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Description)
                                    </td>
                                </tr>
                            }
                        </tbody>
                        <tfoot>
                            <tr>
                                <th>Requested By</th>
                                <th>Request Type</th>
                                <th>From</th>
                                <th>To</th>
                                <th>Requested Amount</th>
                                <th>Status</th>
                                <th>Comments</th>
                            </tr>
                        </tfoot>
                    </table>

                </div>
            </div>
        </div>
    </div>

</div>

@section Scripts {

    <script src="/lib/jquery/dist/jquery.js"></script>
    <script src="/lib/Popper/popper.min.js"></script>
    <script src="/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="/lib/metisMenu/dist/jquery.metisMenu.js"></script>
    <script src="/lib/slimScroll/jquery.slimscroll.js"></script>
    <script src="/lib/pace/pace.js"></script>
    <script src="/js/script.js?v=Z0lG-W-_b5obPSVMDKOODB1S9RZ_0pOI0YMGLlVehZc"></script>

    <!-- Only for demo purpose -->
    <script src="/js/skin.config.js"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css">

    <script src="https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/select2@3.5.2-browserify/select2.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@3.5.2-browserify/select2.min.js"></script>
    <environment names="Development,Staging,Production">
        <link rel="stylesheet" href="~/lib/dataTables/datatables.min.css" />
    </environment>

    @*Datatables scripts*@
    <environment names="Development,Staging,Production">
        <script src="~/lib/dataTables/datatables.min.js"></script>
        <script src="~/lib/dataTables/dataTables.bootstrap4.min.js"></script>
    </environment>

    <script type="text/javascript">
        $(document).ready(function () {
            $('.dataTables-example').DataTable({
                pageLength: 25,
                dom: '<"html5buttons"B>lTfgitp',
                buttons: [
                    { extend: 'copy' },
                    { extend: 'csv' },
                    { extend: 'excel', title: 'ExampleFile' },
                    { extend: 'pdf', title: 'ExampleFile' },
                    {
                        extend: 'print',
                        customize: function (win) {
                            $(win.document.body).addClass('white-bg');
                            $(win.document.body).css('font-size', '10px');
                            $(win.document.body).find('table')
                                .addClass('compact')
                                .css('font-size', 'inherit');
                        }
                    }
                ]
            });
        });
    </script>
}

Views/Approver/Index.cshtml
@*
    *********************************
    View displaying employee requests
    for the logged in approver user
    *********************************
*@
@model HolidayTracker.ViewModels.ApprovalsViewModel;
@{
    ViewData["Title"] = "Requests";
}

<div class="text-center">
    <h4 class="display-4">Employees' requests</h4>
    <p>These are requests of employees assigned to you</p>
</div>

<h2>Pending Requests</h2>
<p>
    <a asp-action="DisplayAllRequests">View Request History</a>
</p>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox ">
                <div class="ibox-title">
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">

                    <table class="table table-striped table-bordered table-hover dataTables-example">
                        <thead>
                            <tr>
                                <th>Requested By</th>
                                <th>Request Type</th>
                                <th>From</th>
                                <th>To</th>
                                <th>Requested Amount</th>
                                <th>Status</th>
                                <th>Comments</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Requests)
                            {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Employee.DisplayName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.RequestType.RequestTypeName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.From)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.To)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.RequestAmount)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.DisplayStatus)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Description)
                                </td>
                                <td>
                                    <input type="button" value="Approve" data-id="@item.Id" class="btn btn-primary approve" />
                                    <input type="button" value="Reject" data-id="@item.Id" class="btn btn-danger reject" />
                                    <input type="button" value="Cancel" data-id="@item.Id" class="btn btn-info cancel" />
                                </td>
                            </tr>
                            }
                        </tbody>
                        <tfoot>
                            <tr>
                                <th>Requested By</th>
                                <th>Request Type</th>
                                <th>From</th>
                                <th>To</th>
                                <th>Requested Amount</th>
                                <th>Status</th>
                                <th>Comments</th>
                                <th>Actions</th>
                            </tr>
                        </tfoot>
                    </table>

                </div>
            </div>
        </div>
    </div>

</div>

@section Scripts {

<script src="/lib/jquery/dist/jquery.js"></script>
<script src="/lib/Popper/popper.min.js"></script>
<script src="/lib/bootstrap/dist/js/bootstrap.js"></script>
<script src="/lib/metisMenu/dist/jquery.metisMenu.js"></script>
<script src="/lib/slimScroll/jquery.slimscroll.js"></script>
<script src="/lib/pace/pace.js"></script>
<script src="/js/script.js?v=Z0lG-W-_b5obPSVMDKOODB1S9RZ_0pOI0YMGLlVehZc"></script>

<!-- Only for demo purpose -->
<script src="/js/skin.config.js"></script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css">

<script src="https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
<link href="https://cdn.jsdelivr.net/npm/select2@3.5.2-browserify/select2.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@3.5.2-browserify/select2.min.js"></script>
<environment names="Development,Staging,Production">
    <link rel="stylesheet" href="~/lib/dataTables/datatables.min.css" />
</environment>

    @*Datatables scripts*@
<environment names="Development,Staging,Production">
    <script src="~/lib/dataTables/datatables.min.js"></script>
    <script src="~/lib/dataTables/dataTables.bootstrap4.min.js"></script>
</environment>

<script type="text/javascript">
    $(document).ready(function () {
        $('.dataTables-example').DataTable({
            pageLength: 25,
            dom: '<"html5buttons"B>lTfgitp',
            buttons: [
                { extend: 'copy' },
                { extend: 'csv' },
                { extend: 'excel', title: 'ExampleFile' },
                { extend: 'pdf', title: 'ExampleFile' },
                {
                    extend: 'print',
                    customize: function (win) {
                        $(win.document.body).addClass('white-bg');
                        $(win.document.body).css('font-size', '10px');
                        $(win.document.body).find('table')
                            .addClass('compact')
                            .css('font-size', 'inherit');
                    }
                }
            ]
        });
        $(".approve").click(function () {
            $.ajax({
                type: "POST",
                url: "@Url.Action("ApproveRequest", "Approver")",
                data: {
                    Id: $(this).attr('data-id')
                },
                success: function (response) {
                    alert('Request Approved!');
                    location.reload();
                },
                error: function (e) {
                    alert('Error!');
                }
            });
        });
        $(".reject").click(function () {
            $.ajax({
                type: "POST",
                url: "@Url.Action("RejectRequest", "Approver")",
                data: {
                    Id: $(this).attr('data-id')
                },
                success: function (response) {
                    alert('Request Rejected!');
                    location.reload();
                },
                error: function (e) {
                    alert('Error!');
                }
            });
        });
        $(".cancel").click(function () {
            $.ajax({
                type: "POST",
                url: "@Url.Action("CancelRequest", "Approver")",
                data: {
                    Id: $(this).attr('data-id')
                },
                success: function (response) {
                    alert('Request Cancelled!');
                    location.reload();
                },
                error: function (e) {
                    alert('Error!');
                }
            });
        });
    });
</script>
}